Fix sort mistake in pandas dataframe
When I run SAP fit_predict I got a mistake "AttributeError: 'DataFrame' object has no attribute 'sort'" which caused by this line